services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8181:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:L+kULBJF9E6jpQIZ9yheZxLgqJ0YQlEzkr3NaJScJ9I= # How to generate an app key: https://speedtest-tracker.dev/
            - APP_URL=http://192.168.1.136
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=0 */1 * * * # optional: schedule a speedtest with an cronjob https://crontab.gur
            - APP_TIMEZONE=America/Chicago
        volumes:
            - ./config:/config
            - /path/to-custom-ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
