---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings
title: local.dashboard
background:
  image:  https://i.ibb.co/hMWFX6D/mountain-clouds.gif
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
theme: dark
color: stone



providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  finnhub: ct18r41r01qkcukbo3cgct18r41r01qkcukbo3d0

