---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- resources:
- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: long
   # ^^^ add this block

- weatherapi:
    label: Evansdale # optional
    latitude: 42.4692   
    longitude: 92.2810 
    units: imperial # or imperial
    apiKey: 563ed91941554729bba185223242311
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
- stocks:
    provider: finnhub
    color: true # optional, defaults to true
    cache: 1 # optional, default caches results for 1 minute
    watchlist:
      - PLTR
      - UEC
      - SPY
      - QQQ
      - TSLA
      - AG
      - MSTR
